Probabilistic landfast ice from CICE
NOAA-GFDL/SIS2 pull request #162
Opened 2021-12-21 22:22 UTC by kshedstrom

A different way to do landfast ice, unpublished as yet by the Canadians.

2021-12-29 16:55 UTC, Hallberg-NOAA commented on src/SIS_dyn_cgrid.F90
> +      if (atot > 0.05 .and. m_i > 0.01 .and. sea_lev(i,j) < max_depth) then
There are dimensionally inconsistent comparisons and hard-coded dimenesional constansts here. Both m_i and sea_lev have units here of [Z ~> m], while max_depth is a hard-coded number with units of [m], and 0.01 is presumbly 0.01 [m].  Please correct the units, and verify that the rescaling is correct by trying out a test case with various values Z_RESCALE_POW and R_RESCALE_POW.

2021-12-29 16:58 UTC, Hallberg-NOAA commented on src/SIS_dyn_cgrid.F90
> +  real :: wid_i, wid_b, mu_i, sigma_i, mu_b, m_i, v_i !  parameters for PDFs
Please add comments describing the purpose and units of each of these real variables.

2021-12-29 17:04 UTC, Hallberg-NOAA commented on src/SIS_continuity.F90
> +    print *, 'Negative ice thickness at:', i+G%idg_offset, j+G%jdg_offset, k, h(i,j,:)
We have been encouraged not to write directly to stdout using `write (*,*)` or `print *` to prepare for machines where not all PEs are able to access the I/O channels, and we are not doing so elsewhere in the MOM6 or SIS2 code.

  Please revise these useful messages to write to a message string, and then either concatenate this message string to the following `SIS_error(FATAL, ...)` call, or as 'call SIS_error(WARNING, mesg, all_print=.true.)` before the fatal error message, and similarly for the other 5 new error messages in this file and the other new error message in SIS_transport.F90 using the similar `print *,...` construct.

2021-12-29 17:07 UTC, Hallberg-NOAA requested changes
Overall, this PR looks like a valuable new contribution, but I believe that there are some expressions that do not have the appropriate dimensional consistency verification and there are some error messages that do not follow the I/O pattern we have been advised to use.  Please consider making the changes suggested in the specific comments on parts of the code involved in this PR.

2021-12-30 18:57 UTC, kshedstrom commented
Thank you for all your suggestions!

1. For the scalings, do you do MOM_override and SIS_override together or independently? Either should work? Both Z and R rescalings are problematic for me. Do you have debugging hints?

2. I have gotten rid of the print statements, however the following compiles, but doesn't run:
```
write(mesg,'("Negative ice volume after ridging: ", 2i6, 2x, (1pe12.4))') i+G%jdg_offset, j+G%jdg_offset, aicen, vicen
```

2022-02-14 19:15 UTC, kshedstrom commented
Thanks, yes, I was getting a mismatch with my illegal print statements.

2022-02-16 02:46 UTC, Hallberg-NOAA commented on src/SIS_dyn_cgrid.F90
> +           ncat_b = 100, &  ! number of bathymetry categories
Given that there are some operations that occur ncat_b x ncat_i times for each grid cell, it seems dangerous to specify these as (large) fixed parameters.  It is hard-coded that this routine will do 10,000 operations at every grid point that is both shallow and has enough ice.  It seems to me that these sizes should be model variables that can be determined and set at run-time.

2022-02-16 02:49 UTC, Hallberg-NOAA commented on src/SIS_dyn_cgrid.F90
> +        do n=1, ncat_i
This line is hard-coded to run 10,000 times for every model grid cell.  This seems inflexible and possibly excessive?  I think that the values of ncat_i and ncat_b should be something that can be set at run-time.

2022-02-16 02:55 UTC, Hallberg-NOAA reviewed
I have now read through this PR, and I agree that most of this seems like the right thing to do.  However, I do not like that the sizes of the ice and bathymetry distributions are both set at 100 elements, leading to a 10,000 step operation at some points.  I think that these sizes should be runtime configurable parameters, and not hard-coded.

Also, I do not like that this new ITD_LANDFAST capability by design does not work with MERGED_CONTINUITY, which is supposed to be the direction we are going with our ice-ocean coupling.  Is there a fundamental and irreconcilable conflict, or is the error message just a placeholder until we get the chance to try to get these two options working together?

2022-02-18 00:09 UTC, kshedstrom commented
I had to go digging to remind myself why I didn't think it worked with MERGED_CONTINUITY. The Lemieux scheme is called from either SIS_merged_dyn_cont or from SIS_dynamics_trans. The ITD scheme needs the ice thickness distribution which is not currently passed to SIS_merged_dyn_cont since it only wants the simplified state. Would you object to having it know about the ITD just for this?

Yes, I agree that 10,000 iterations seems like a lot. I will add some more runtime parameters.

2022-03-05 13:55 UTC, Hallberg-NOAA approved these changes
These changes have addressed the concerns that I had with the previous version.

2022-03-05 19:39 UTC, merged